### PR TITLE
CRIU: Heap Resizing on restore

### LINKED ISSUE #1375: CRIU: Heap Resiszing on restore
**Issue or pull request number:**
https://github.com/eclipse-openj9/openj9/issues/18217

**Overview:**
*Describe the external change and the impact/benefit from a user perspective.*

**Release target:**
Eclipse OpenJ9 0.46.0

**Applies to the following JDK versions:**
E.g. 11 and later

**Applies to the following platforms:**
 Linux X|P|Z|A 

**For new command line options:**

- Option name and syntax: -XdynamicHeapAdjustment
- If values are set:
	- None
- Purpose:
   -  This option turns on a JVM capaiblity that autimatically adjusts Xmx and Xms such that they are withinn the bounds for the physical memory limitations on the system.
- Restrictions:
   - Can only be used with `-XX:+EnableCRIUSuport`

### PR DESCRIPTION
**Pull request by Sreekala-Gopakumar**
https://github.com/eclipse-openj9/openj9-docs/issues/1375

New option -XdynamicHeapAdjustment added. Related topics updated.

Closes #1375
Signed-off-by: Sreekala Gopakumar sreekala.gopakumar@ibm.com

### CODE REVIEW

**Comment by Sreekala-Gopakumar** [comment]
Jenkins doc stage

**Comment by Sreekala-Gopakumar** [comment]
@tajila - I have updated the documents. Please check and let me know if any changes are required. Thanks!

**Comment by Sreekala-Gopakumar** [comment]
> @tajila - I have updated the documents. Please check and let me know if any changes are required. Thanks!

@tajila - Could you please check and confirm. Thanks!

**Review by tajila — APPROVED** [review]

**Comment by Sreekala-Gopakumar** [comment]
@amicic - Could you please check and confirm the content? This has to be finalised as soon as possible for 0.46.0 release. Thanks!

**Comment by tajila** [comment]
> @amicic - Could you please check and confirm the content? This has to be finalised as soon as possible for 0.46.0 release. Thanks!

Aleks may be away for some time. I think this is ready to go.

**Pull request merged**
