### PR TITLE
Removal of AArch64 macOS from early access in 0.35

### PR DESCRIPTION
**Pull request by pshipton**
Cherry pick the changes from https://github.com/eclipse-openj9/openj9-docs/pull/1010 to the 0.35 branch.

### CODE REVIEW

**Comment by keithc-ca** [comment]
Jenkins copyright check

**Review by keithc-ca — APPROVED** [review]
I would have preferred the commits be squashed, but I won't insist.

**Comment by pshipton** [comment]
I would have squashed them if asked, and realized I should have asked for the original changes to be squashed before I merged them.

**Comment by keithc-ca** [comment]
Yes, I'm sure you would have squashed the commits here had I asked, but given they weren't in #1010, I didn't ask, and, yes, it would have been better had #1010 been a single commit.

**Pull request merged**
