### PR TITLE
TGC allocation

### PR DESCRIPTION
**Pull request by amicic**
Add description for (an already existing, but recently enhnaced) -Xtgc:allocation option

Related to https://github.com/eclipse-openj9/openj9/pull/19070

### CODE REVIEW

**Comment by pshipton** [comment]
You might was to create an issue instead of a PR. Sreekala will want an issue for tracking, and will make the actual changes. The What's New should be updated, and the release notes. This is for 0.46 so we can't merge it now.

**Comment by keithc-ca** [comment]
Can you rebase this on a more recent commit (the base is from 2022), please, and fix the line ending check failure.

**Comment by keithc-ca** [comment]
Please also fix the typo in the description and commit message (enhnaced -> enhanced).

**Comment by pshipton** [comment]
I'd just create the issue and close this.

**Comment by amicic** [comment]
Replaced by https://github.com/eclipse-openj9/openj9-docs/pull/1381

**Pull request closed without merging**
