### PR TITLE
Supported environments - Release date 0.43.0

### PR DESCRIPTION
**Pull request by Sreekala-Gopakumar**
Updated the release date for 0.43.0 release. Removed column for JDK20 and rows for the earlier releases (0.38.0 and 0.39.0)

Signed-off-by: Sreekala Gopakumar <sreekala.gopakumar@ibm.com>

### CODE REVIEW

**Comment by pshipton** [comment]
jenkins doc stage

**Comment by pshipton** [comment]
We should fix 0.42 as well, which shipped in Jan.
Also we hope to include jdk22 in 0.44.

**Comment by Sreekala-Gopakumar** [comment]
> We should fix 0.42 as well, which shipped in Jan. Also we hope to include jdk22 in 0.44.

So will 0.44.0 release be a feature release that supports a new OpenJDK release only, in this case only JDK22?

**Comment by pshipton** [comment]
0.44 will deliver 8, 11, 17, 21 and will include 22 if it's ready, otherwise we'll deliver 22 at a later time.

**Comment by Sreekala-Gopakumar** [comment]
> 0.44 will deliver 8, 11, 17, 21 and will include 22 if it's ready, otherwise we'll deliver 22 at a later time.

Then, we can add the JDK22 column to the table in the next release only if we are able to deliver it, right? Right now, I will retain the existing columns only, JDK8, 11, 17 and 21?

**Comment by pshipton** [comment]
ok

**Comment by Sreekala-Gopakumar** [comment]
Jenkins doc stage

**Comment by Sreekala-Gopakumar** [comment]
@pshipton - I have updated the topic. Please check and confirm. Thanks!

**Review by pshipton — APPROVED** [review]

**Pull request merged**
