### PR TITLE
OpenJDK jdk17 is supported on OSX 10.14+, jdk18 on 10.15+

### PR DESCRIPTION
**Pull request by pshipton**
https://wiki.openjdk.java.net/display/Build/Supported+Build+Platforms

https://www.oracle.com/java/technologies/javase/products-doc-jdk17certconfig.html
https://www.oracle.com/java/technologies/javase/products-doc-jdk18certconfig.html

### CODE REVIEW

**Review by keithc-ca — APPROVED** [review]

**Comment by keithc-ca** [comment]
Jenkins doc stage

**Comment by keithc-ca** [comment]
Hmm. https://www.oracle.com/java/technologies/javase/products-doc-jdk17certconfig.html lists both 10.14 and 10.15 for macOS/x64. Perhaps this should say 10.14 instead of 10.15?

**Comment by pshipton** [comment]
Good catch, somehow I missed that.

**Comment by pshipton** [comment]
Updated.

**Comment by keithc-ca** [comment]
https://eclipse-openj9.github.io/openj9-docs-staging/912/ looks good; I don't think we need another build for the latest (one character) change.

**Pull request merged**
