### PR TITLE
Release 0.45.0 What's new with JEPS

### PR DESCRIPTION
**Pull request by Sreekala-Gopakumar**
Created the What's new in version 0.45.0 topic and added the JEPS list for JDK 22. Added the icons for Java 22 and Java 22 plus. Updated the mkdocs file.

Signed-off-by: Sreekala Gopakumar sreekala.gopakumar@ibm.com

### CODE REVIEW

**Comment by Sreekala-Gopakumar** [comment]
Jenkins doc stage

**Comment by pshipton** [comment]
@tajila does the list of JEPs look correctly categorized?

**Comment by tajila** [comment]
`Structured Concurrency (Second Preview)` should be in the  "supported by OpenJ9:" list

**Comment by pshipton** [comment]
When I asked @babsingh about Structured Concurrency, he mentioned there were no OpenJ9 changes required to support this JEP in Java 22.

**Comment by tajila** [comment]
> When I asked @babsingh about Structured Concurrency, he mentioned there were no OpenJ9 changes required to support this JEP in Java 22.

Okay we can go with that then. Babneet is more familiar with what changed in that area.

**Comment by babsingh** [comment]
> there were no OpenJ9 changes required to support this JEP in Java 22.

explicitly, no. but, structured concurrency is built on top of virtual threads. openj9's implementation of virtual threads will indirectly influence the implementation of structured concurrency.

@fengxue-IS any more points to add on structured concurrency?

**Comment by fengxue-IS** [comment]
> > there were no OpenJ9 changes required to support this JEP in Java 22.
> 
> explicitly, no. but, structured concurrency is built on top of virtual threads. openj9's implementation of virtual threads will indirectly influence the implementation of structured concurrency.
> 
> @fengxue-IS any more points to add on structured concurrency?

No, there have not been any major updates to structured concurrency JEP in 22

**Review by pshipton — APPROVED** [review]

**Pull request merged**
