### PR TITLE
Miscellaneous tasks for 0.42.0 release

### PR DESCRIPTION
**Pull request by Sreekala-Gopakumar**
Created a new topic - Migrating from Java 17 to Java 21 and included the JEPs for Java 21 in the What's new in version 0.42.0

Signed-off-by: Sreekala Gopakumar <sreekala.gopakumar@ibm.com>

### CODE REVIEW

**Comment by Sreekala-Gopakumar** [comment]
Jenkins doc stage

**Comment by Sreekala-Gopakumar** [comment]
Jenkins doc stage

**Comment by Sreekala-Gopakumar** [comment]
@pshipton  - I have added the JEPs for Java 21 in What's new in version 0.42.0 topic and added the Migrating from Java 17 to Java 21 topic. Please check and let me know if any other information should be added in this topic. Thanks!

**Review by pshipton — APPROVED** [review]

**Comment by pshipton** [comment]
There is a feature listed in the 11 -> 17 migration about the compiler levels. Builds of 21 use newer compilers, although as of 0.43 all versions will use the same gcc 11.2 and VS2022 levels.

**Comment by Sreekala-Gopakumar** [comment]
> There is a feature listed in the 11 -> 17 migration about the compiler levels. Builds of 21 use newer compilers, although as of 0.43 all versions will use the same gcc 11.2 and VS2022 levels.

So do we need to add this information about the new compilers in 0.42.0 release or make the change in 0.43.0 release?

**Comment by pshipton** [comment]
Java 21 uses new compilers compared to Java 17. Since we included that info for 11 vs 17, we can do the same for 21. You can compare the tables for 17 and 21 and add a line for the differences.
https://eclipse-openj9.github.io/openj9-docs/openj9_support/

**Pull request merged**
