### PR TITLE
Add missing Xtgc options

### PR DESCRIPTION
**Pull request by amicic**
Signed-off-by: Aleksandar Micic <amicic@ca.ibm.com>

### CODE REVIEW

**Comment by amicic** [comment]
@dmitripivkine @pshipton

**Comment by pshipton** [comment]
Are these recently added options, or options that have been missing for quite some time? If recently added pls refer to the PR(s) which added them.

**Comment by amicic** [comment]
Very old ones.

**Review by pshipton — APPROVED** [review]

**Comment by pshipton** [comment]
jenkins doc stage

**Comment by pshipton** [comment]
jenkins doc stage

**Pull request merged**
