### PR TITLE
Create api doc for jdk19 0.37

### PR DESCRIPTION
**Pull request by pshipton**
The javadoc was created by https://openj9-jenkins.osuosl.org/job/Build_JDK19_aarch64_mac_Personal/191/

### CODE REVIEW

**Comment by pshipton** [comment]
jenkins doc stage

**Comment by pshipton** [comment]
I'll need to fix this for https://github.com/eclipse-openj9/openj9/pull/16915

**Comment by pshipton** [comment]
jenkins doc stage

**Comment by keithc-ca** [comment]
This is missing the openj9.criu module. Perhaps it should be included even though it doesn't apply to all platforms?

**Comment by pshipton** [comment]
I need to generate the doc on xlinux then, and it should be automatically included.

@tajila I assume including openj9.criu javadoc is expected?

**Comment by pshipton** [comment]
Actually, we aren't supporting criu on 0.37 or jdk19 afaik.

**Pull request merged**
