### PR TITLE
Update jdk21 api docs for 0.42 and 0.43

### PR DESCRIPTION
**Pull request by pshipton**
Built via
https://openj9-jenkins.osuosl.org/job/Pipeline-Build-Javadoc/170/

### CODE REVIEW

**Comment by pshipton** [comment]
I've set the 0.43 doc PRs for jdk8, 11, 17 as draft as this PR for 0.42 and 0.43 should be merged first.

**Comment by babsingh** [comment]
jenkins doc stage

**Comment by babsingh** [comment]
LGTM. Verified the content at https://eclipse-openj9.github.io/openj9-docs-staging/1236/api-jdk21.

**Review by babsingh — APPROVED** [review]

**Comment by babsingh** [comment]
> I've set the 0.43 doc PRs for jdk8, 11, 17 as draft as this PR for 0.42 and 0.43 should be merged first.

Is the merge order going to be 17 -> 11 -> 8?

**Comment by pshipton** [comment]
The merge order of 8, 11, 17 doesn't matter. I just wanted the 0.42 change first.

**Comment by pshipton** [comment]
It saves me from having to cherry pick the change and create another PR for the 0.42 branch. Merging it first allowed it to be pushed to the 0.42 branch.

**Pull request merged**
