### PR TITLE
Starting with release 0.32.0 JITServer is supported on zLinux as well

### PR DESCRIPTION
**Pull request by mpirvu**
Issue: #927

Signed-off-by: Marius Pirvu <mpirvu@ca.ibm.com>

### CODE REVIEW

**Comment by pshipton** [comment]
Pls update the release notes as well. 
https://www.eclipse.org/openj9/docs/version0.32/

**Comment by mpirvu** [comment]
Created openj9 PR  https://github.com/eclipse-openj9/openj9/pull/14966 to update doc/release-notes/0.32/0.32.md

**Comment by doveye** [comment]
Jenkins doc stage

**Review by doveye — APPROVED** [review]
You only need to trademark the first occurrence of a term, in normal text (terms don't need to be trademarked in titles). Plus these days it's just "IBM Z" rather than "IBM Z systems". But they are minor issues and this release has already gone out so I'm going to approve. We can make a note to tweak the text in future.

**Comment by mpirvu** [comment]
> In the openj9 release notes it mentions JIT server (for Z) is only supported on 8, 11, 17. I don't see this limitation mentioned in the User Guide.

There is nothing known that prevents us to declare support for non LTS Java releases. It was a decision to limit exposure to just LTS Java. The same pattern was used with previous releases: the release notes only claimed support for Java8/11 and Java17 when it was released.
I can modify the User Guide to be more specific (i.e. say that only Java8/11/17 are supported)

**Comment by pshipton** [comment]
> I can modify the User Guide to be more specific (i.e. say that only Java8/11/17 are supported)

Up to you, I was just pointing it out. I doubt we can expect user's to be aware of something announced in some old release notes.

**Pull request merged**
