### PR TITLE
General doc tidying for 0.27

### PR DESCRIPTION
**Pull request by doveye**
Correct a few issues in the docs - trademarks, text formatting, blurb about binaries in "Release notes".

Signed-off-by: Esther Dovey <doveye@uk.ibm.com>

### CODE REVIEW

**Comment by doveye** [comment]
Jenkins doc stage

**Comment by doveye** [comment]
Jenkins doc stage

**Comment by doveye** [comment]
Jenkins doc stage

**Comment by doveye** [comment]
@keithc-ca could you please merge this one too - it's just some minor doc fixes and I've checked they all look ok in the draft docs. Thanks

**Review by keithc-ca — APPROVED** [review]

**Pull request merged**
