### PR TITLE
Adjust -XX:MaxDirectMemorySize defaults

### PR DESCRIPTION
**Pull request by pshipton**
Fixes https://github.com/eclipse-openj9/openj9-docs/issues/905

### CODE REVIEW

**Comment by pshipton** [comment]
jenkins doc stage

**Comment by pshipton** [comment]
https://eclipse-openj9.github.io/openj9-docs-staging/907

**Comment by pshipton** [comment]
I need to add a release note.

**Comment by pshipton** [comment]
jenkins doc stage

**Comment by pshipton** [comment]
jenkins doc stage

**Comment by pshipton** [comment]
jenkins doc stage

**Comment by pshipton** [comment]
https://eclipse-openj9.github.io/openj9-docs-staging/907/version0.31/
https://eclipse-openj9.github.io/openj9-docs-staging/907/xxmaxdirectmemorysize/

**Review by keithc-ca — APPROVED** [review]

**Pull request merged**
