### PR TITLE
Update supported platforms topic for 0.36.0

### PR DESCRIPTION
**Pull request by Sreekala-Gopakumar**
https://github.com/eclipse-openj9/openj9-docs/issues/1035

Updated the supported platforms topic

Signed-off-by: Sreekala Gopakumar <sreekala.gopakumar@ibm.com>

### CODE REVIEW

**Comment by Sreekala-Gopakumar** [comment]
Jenkins doc stage

**Comment by Sreekala-Gopakumar** [comment]
@doveye - I have updated the supported environments topic for 0.36.0 release.

**Comment by pshipton** [comment]
0.37 is for jdk20, which isn't listed. jdk18 can be removed from the table, to make room, it's out of support. It's not clear that 0.37 will deliver on time, in March, it seems likely it will be late.

0.38 doesn't support jdk19, it would support jdk20 if jdk20 is ready.

**Comment by Sreekala-Gopakumar** [comment]
> 0.37 is for jdk20, which isn't listed. jdk18 can be removed from the table, to make room, it's out of support. It's not clear that 0.37 will deliver on time, in March, it seems likely it will be late.
> 
> 0.38 doesn't support jdk19, it would support jdk20 if jdk20 is ready.

JDK20 is listed as the last column. Scroll bar can be used. If JDK18 column is to be removed then can I remove 0.33.0 release row since 0.33 supports JDK18?

What tentative date should I give for 0.37.0 release?

Thanks!

**Comment by pshipton** [comment]
> If JDK18 column is to be removed then can I remove 0.33.0 release row since 0.33 supports JDK18?

Yes.

> What tentative date should I give for 0.37.0 release?

We don't have enough information yet. Just leave it as-is, but remove jdk19 from 0.38.

**Comment by pshipton** [comment]
Pls remove jdk19 from 0.36.0, since we know this release won't include jdk19. There may be a 0.36.1 to support jdk19 but TBD so it shouldn't be added to the chart.

**Comment by pshipton** [comment]
What we could do for jdk20 is update Note 2 to indicate the March date is tentative and may be delayed.

**Comment by Sreekala-Gopakumar** [comment]
Jenkins doc stage

**Comment by Sreekala-Gopakumar** [comment]
@pshipton - Incorporated the changes. Please check and confirm. Thanks!

**Comment by pshipton** [comment]
The changes lgtm, but there are some doubts the table in it's current form is the best way to present the information. Below is an update about the (possible) upcoming jdk19 and jdk20 releases.

JDK19 isn't currently supported since it's not yet ready to release. The remaining problems are in the milestone plan https://github.com/eclipse-openj9/openj9/milestone/35.

We are still working on it, but once the April release comes out, jdk19 is out of support and we can no longer release it. What we hope to do is get jdk19 ready and release it as 0.36.1 before April, however I can't predict if we'll be able to do this or not, i.e. get all the remaining problems resolved in time. The closer we get to April, the less likely it will be that we will proceed with a jdk19 release. If we skip jdk19, we will continue working on jdk20.

Since jdk19 isn't ready for release, jdk20 also isn't ready. jdk20 depends on having a working jdk19, and also there are new features in jdk20 we need to support. I also can't predict when we will be ready to release jdk20. There is a milestone plan for jdk20 as well https://github.com/eclipse-openj9/openj9/milestone/40.

**Comment by doveye** [comment]
The para before the table makes it clear that the JDK version support and release dates are expected but subject to change. There's also a link to the release notes after the table notes. So maybe we add a 0.36.1 row to the table for JDK 19 and add more detailed info in the release notes to explain that JDK 19 support might be skipped altogether (and JDK 20 delayed) depending on the status of the items in the milestone plans. Then the table is consistent with how it's always been/what users expect to see, but there is more info in the release notes to explain the current, unusual situation.

Thoughts/opinions?

**Comment by pshipton** [comment]
Sounds good to me. There is no guarantee that jdk19 will be 0.36.1, as this release number may be consumed for jdk8, 11, 17 if we find we need to do an update after 0.36.0 for any reason.

**Comment by Sreekala-Gopakumar** [comment]
Jenkins doc stage

**Comment by pshipton** [comment]
To reduce the amount of work required, I expect a 0.36.x release (which may be 0.36.1) to support Java 17 will be specific to Java 19 and not support 8, 11, 17.

**Comment by Sreekala-Gopakumar** [comment]
Jenkins doc stage

**Comment by Sreekala-Gopakumar** [comment]
Updated the document. Thanks!

**Comment by pshipton** [comment]
The table lgtm.

**Comment by Sreekala-Gopakumar** [comment]
Any other changes required? If nothing else is there, could you please merge the documents. Thanks!

**Comment by pshipton** [comment]
Requested a review from Marius for the JITServer changes. The machines that re-build the docs aren't available atm. We can wait to merge it until the machines are back.

**Review by mpirvu — APPROVED** [review]
Changes look good to me

**Review by pshipton — APPROVED** [review]

**Pull request merged**
