### PR TITLE
(0.46.1) Release 0.46.1 What's new topic

### PR DESCRIPTION
**Pull request by pshipton**
Cherry pick https://github.com/eclipse-openj9/openj9-docs/pull/1401
and https://github.com/eclipse-openj9/openj9-docs/pull/1403
and port https://github.com/eclipse-openj9/openj9-docs/pull/1399 fixing the merge conflict.

### CODE REVIEW

**Comment by keithc-ca** [comment]
Jenkins doc stage

**Comment by keithc-ca** [comment]
Perhaps we should add a row in the releases table for 0.46.1 (like we had for 0.29.1)?

**Comment by pshipton** [comment]
@Sreekala-Gopakumar can you pls update the releases table, https://github.com/eclipse-openj9/openj9-docs/pull/1402#issuecomment-2332644302

**Comment by pshipton** [comment]
Jenkins doc stage

**Review by keithc-ca — APPROVED** [review]

**Pull request merged**
