### PR TITLE
Openj9 docs 0.27.0

### PR DESCRIPTION
**Pull request by AdamBrousseau**
Built on
https://github.com/eclipse-openj9/openj9/commit/1851b0074f87e20c0007c6190c745dab9760eabe
https://github.com/eclipse-openj9/openj9-omr/commit/9db1c870dfbaf4cf677cb7ba086ea303e83d7d81
https://github.com/ibmruntimes/openj9-openjdk-jdk8/commit/de702c317454d1cf9ad264f15a8fb2d1431d7006
https://github.com/ibmruntimes/openj9-openjdk-jdk11/commit/21849e2ca05db8c5bb1efb8fc335d8931dec81bf
https://github.com/ibmruntimes/openj9-openjdk-jdk16/commit/34df42439f3be06211b15569253d33921591eb1d

### CODE REVIEW

**Comment by AdamBrousseau** [comment]
For some reason I thought Sue had told me the repo org changes would happen in some build automatically so I'm surprised to see them here still. I thought I had taken them out of my 26 changes because of this. Maybe I'm confused.

Also not sure why that container build launched. It appears to be configured correctly so it shouldn't have fired.

**Comment by keithc-ca** [comment]
I also notice a large addition for `com.ibm.j9ddr.*` that I wasn't expecting, but is likely a consequence of eclipse-openj9/openj9#13040.

**Comment by pshipton** [comment]
Pls rebase or redo this so we can see changes from https://github.com/eclipse-openj9/openj9-docs/pull/811 which is now merged.

**Comment by pshipton** [comment]
Also it should target the openj9-docs-0.27.0 branch.

**Comment by AdamBrousseau** [comment]
Updated, no diff for 8

**Comment by pshipton** [comment]
I don't see any value in merging this.

**Pull request closed without merging**
