### PR TITLE
Apidoc update july2021

### PR DESCRIPTION
**Pull request by AdamBrousseau**

### CODE REVIEW

**Comment by pshipton** [comment]
@doveye we want to merge this head stream update first to pick up all the major changes, and then do another build for 0.27 and see what's changed. Do you need to stage and check things, or can this just be merged?

**Comment by doveye** [comment]
@pshipton we wouldn't be checking technical updates but it would be good to check the general appearance is still ok. Since we have a 0.27 branch for the docs though, I guess we could just merge the head stream, then check that before we merge the 0.27 version. 
BTW, the link to the OpenJ9 repo (gets added to the bottom of each API doc page) should change due to the general project moves. Not sure if that has been done already (looks like there's a redirect in place so not essential) but it's something else we can check.

**Comment by pshipton** [comment]
> Not sure if that has been done already

Yes, it's part of this change.

**Comment by pshipton** [comment]
I've pushed this change to the openj9-docs-0.27.0 branch as well, and we'll update the branch via https://github.com/eclipse-openj9/openj9-docs/pull/806 if necessary to correspond to the 0.27 release.

**Comment by pshipton** [comment]
I was hoping these changes would show up at https://eclipse-openj9.github.io/openj9-docs but they have not so far. @doveye do you need to do something to rebuild the docs?

**Comment by AdamBrousseau** [comment]
Looks like we didn't get an automated build. I kicked one
https://openj9-jenkins.osuosl.org/view/Website-Doc/job/Build-Doc-Push_to_ghpages/13/
Should be up shortly

**Comment by doveye** [comment]
Looks good, thanks Adam and Peter :)

**Pull request merged**
