### PR TITLE
Update OpenJ9 user docs to latest levels of build dependencies

### PR DESCRIPTION
**Pull request by Sreekala-Gopakumar**
https://github.com/eclipse-openj9/openj9-docs/issues/914

Updated the build dependencies

Signed-off-by: Sreekala Gopakumar <sreekala.gopakumar@ibm.com>

### CODE REVIEW

**Comment by Sreekala-Gopakumar** [comment]
@doveye - Updated the documents. Please check. Thanks!

**Comment by doveye** [comment]
Jenkins doc stage

**Comment by doveye** [comment]
Jenkins doc stage

**Comment by doveye** [comment]
Jenkins doc stage

**Comment by doveye** [comment]
Jenkins doc stage

**Comment by AdamBrousseau** [comment]
Jenkins doc stage

**Comment by AdamBrousseau** [comment]
Jenkins doc stage

**Comment by AdamBrousseau** [comment]
Jenkins doc stage

**Pull request merged**
